/** Auto-generated by tools/optimize-shop-heroes.mjs — do not edit */
export const SHOP_HERO_WEBP_SRCS = new Set<string>([
  '/shop/heroes/apparel.webp',
  '/shop/heroes/catalog.webp',
  '/shop/heroes/essentials.webp',
  '/shop/heroes/lifejacket.webp',
  '/shop/heroes/wakeboarding.webp',
  '/shop/heroes/wakesurfing.webp',
  '/shop/heroes/wb-board.webp',
  '/shop/heroes/wb-boots.webp',
  '/shop/heroes/wb-fin.webp',
  '/shop/heroes/wetsuit.webp',
  '/shop/heroes/ws-board.webp',
])
