-- English dynamic content (name and appointment) is generated by code.
-- Only fixed footer copy remains editable, matching the Chinese workflow.
INSERT INTO public.system_settings (setting_key, setting_value, description)
VALUES (
  'tomorrow_reminder_english_footer_text',
  E'When you arrive, tap "OPEN SESAME" at the bottom of our official LINE account to notify the coaches to open the parking gate.\nPlease park in a yellow space. Do not park in the white spaces. Thank you for your cooperation. 🙏\n\nPlease arrive on time. See you tomorrow! 😊',
  '明日提醒英文結尾文字'
)
ON CONFLICT (setting_key) DO UPDATE
SET
  setting_value = EXCLUDED.setting_value,
  description = EXCLUDED.description;
